<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>be.vlaanderen.omgeving.spiegel</groupId>
    <artifactId>spiegel-parent</artifactId>
    <version>0.1.1-SNAPSHOT</version>
  </parent>

  <artifactId>spiegel-adapter-config</artifactId>
  <name>SPieGeL :: Configuration adapter</name>
  <description>TenantConfigurationPort: tenant configuration from YAML and .rq files.</description>

  <dependencies>
    <dependency>
      <groupId>be.vlaanderen.omgeving.spiegel</groupId>
      <artifactId>spiegel-core</artifactId>
    </dependency>
  </dependencies>
</project>
